services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/src
    env_file:
      - .env
    networks:
      - pt21a-network

  
  postgres: 
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - pt21a-network


volumes:
  postgres_data:
networks:
  pt21a-network:
    driver: bridge

    